name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMG_TAG: adapto-v4-bot:latest
  HOST: rasika.azurecr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3.2.0
      with:
        registry: ${{ env.HOST }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.4.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.HOST }}/${{ secrets.ACR_USER }}/${{ env.IMG_TAG }}
